# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: a052529
_src_path: gh:scipp/copier_template
description: Validate and check NeXus files
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp
orgname: scipp
prettyname: Chexus
projectname: chexus
related_projects: ScippNexus
year: 2024
